#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

autoload bashcompinit && bashcompinit

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

complete -C $(which aws_completer) aws

gcloud_completions_loc=(
    /opt/homebrew
    /usr
)

for loc in $gcloud_completions_loc; do
  completion_path="$loc/share/google-cloud-sdk/completion.zsh.inc"
  if [[ ! -f "$completion_path" ]]; then
    continue
  fi

  source "$completion_path"
done

# Customize to your needs...
alias ls='ls --color=auto -h --group-directories-first'
alias grep='egrep --color=auto'

bindkey "^r" history-incremental-search-backward
bindkey "^s" history-incremental-search-forward

export GPG_TTY=$(tty)
